AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/*.rb'
    - 'interop/*.rb'
