AllCops:
  TargetRubyVersion: 3.1

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 15

Naming/MethodParameterName:
  MinNameLength: 1

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/*.rb'
    - 'interop/*.rb'

# https://github.com/rubocop/rubocop/issues/10258
Layout/BlockAlignment:
  Enabled: false
