AllCops:
  TargetRubyVersion: 2.7

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Naming/MethodParameterName:
  MinNameLength: 1

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/*.rb'
    - 'interop/*.rb'

Layout/LineLength:
  Exclude:
    - 'tttls1.3.gemspec'

# https://github.com/rubocop/rubocop/issues/10258
Layout/BlockAlignment:
  Enabled: false
