name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['4.0']
    env:
      SPEC_VERBOSE: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: docker://thekuwayama/openssl:latest
      - name: Set up Ruby
        uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          gem --version
          gem install bundler
          bundle --version
          bundle install
      - name: Run rubocop
        run: bundle exec rake rubocop
      - name: Run rspec
        run: bundle exec rake spec
      - name: Run interop client
        run: bundle exec rake interop:client
      - name: Run interop server
        run: bundle exec rake interop:server
