name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3', '3.4', '4.0']
    env:
      SPEC_VERBOSE: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: docker://thekuwayama/openssl:latest
      - name: Set up Ruby
        uses: ruby/setup-ruby@0cb964fd540e0a24c900370abf38a33466142735 # v1.305.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false
      - name: Install dependencies
        run: |
          gem --version
          gem install bundler
          bundle --version
          bundle install
      - name: Run rubocop
        run: bundle exec rake rubocop
      - name: Run rspec
        run: bundle exec rake spec
      - name: Run interop client
        run: bundle exec rake interop:client
      - name: Run interop server
        run: bundle exec rake interop:server
