name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3', '3.4', '4.0']
    env:
      SPEC_VERBOSE: true
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: docker://thekuwayama/openssl:latest
      - name: Set up Ruby
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          gem --version
          gem install bundler
          bundle --version
          bundle install
      - name: Run rubocop
        run: bundle exec rake rubocop
      - name: Run rspec
        run: bundle exec rake spec
      - name: Run interop client
        run: bundle exec rake interop:client
      - name: Run interop server
        run: bundle exec rake interop:server
